<a href="https://colab.research.google.com/github/gabrielbaltazarmw2/NumPy/blob/main/01_BASIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Basic: exercícios, prática, solução**

from: https://www.w3resource.com/python-exercises/numpy/basic/index.php

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.4'

In [ ]:
np.show_config()

Escreva um programa NumPy para testar se nenhum dos elementos de uma determinada matriz é zero:

In [37]:
x = np.array([1,2,3,4])
print(x)
print(np.all(x))
z = np.array([0,1,2,3])
print(z)
np.all(z)

[1 2 3 4]
True
[0 1 2 3]


False

Escreva um programa NumPy para testar se algum dos elementos de uma determinada matriz é diferente de zero:

In [46]:
x = np.array([0,0,0,0,1])
print(x)
print(np.any(x))
z = np.zeros(4)
print(z)
print(np.any(z))

[0 0 0 0 1]
True
[0. 0. 0. 0.]
False


Escreva um programa NumPy para testar a finitude de um determinado array elemento a elemento (não infinito ou não um número):

In [50]:
array = np.array([1.0, np.inf, np.nan, 2.5, np.NINF])
print(array)
print(np.isfinite(array))

[ 1.   inf  nan  2.5 -inf]
[ True False False  True False]


Escreva um programa NumPy para testar elementos a infinito positivo ou negativo:

In [52]:
array = np.array([1.0, np.inf, np.nan, 2.5, np.NINF])
print(array)
print(np.isinf(array))
print(np.isneginf(array))

[ 1.   inf  nan  2.5 -inf]
[False  True False False  True]
[False False False False  True]


Escreva um programa NumPy para testar elemento a elemento para NaN de uma determinada matriz:

In [54]:
array = np.array([1.0, np.inf, np.nan, 2.5, np.NINF])
print(array)
print(np.isnan(array))

[ 1.   inf  nan  2.5 -inf]
[False False  True False False]


Escreva um programa NumPy para testar elementos a números complexos, números reais em uma determinada matriz. Teste também se um dado número é do tipo escalar ou não:

In [ ]:
matrix = np.array([[1, 1+1j, 1j],
                   [-1+1j, -1, -1-1j],
                   [-1j, 1-1j, 1]])
print(matrix)
print(np.iscomplex(matrix))
print(np.isreal(matrix))
print(np.isscalar(matrix))
print(matrix.shape)

In [ ]:
print(matrix,"\n")
print(matrix[0:1],"\n")


Escreva um programa NumPy para testar se duas matrizes são iguais em elementos dentro de uma tolerância:

In [109]:
a = np.arange(0,6,1)
b = np.array([0.1, 1.3, 2.2, 3, 4.5, 4.9])
print(a,'\n',b)

print(np.allclose(a, b, atol=0.5))

[0 1 2 3 4 5] 
 [0.1 1.3 2.2 3.  4.5 4.9]
True


Escreva um programa NumPy para criar uma comparação elementar (maior, maior_igual, menor e menor_igual) de duas matrizes fornecidas:

In [115]:
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matriz2 = np.array([[1, 3, 2],
                    [1, 6, 5]])
print(matriz1,'\n')
print(matriz2,'\n')

print(matriz1>matriz2,'\n')
print(matriz1>=matriz2,'\n')
print(matriz1<matriz2,'\n')
print(matriz1<=matriz2,'\n')

[[1 2 3]
 [4 5 6]] 

[[1 3 2]
 [1 6 5]] 

[[False False  True]
 [ True False  True]] 

[[ True False  True]
 [ True False  True]] 

[[False  True False]
 [False  True False]] 

[[ True  True False]
 [False  True False]] 

