<a href="https://colab.research.google.com/github/gabrielbaltazarmw2/NumPy/blob/main/02_MATRIZ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy: exercícios de objeto de matriz, prática, solução:

https://www.w3resource.com/python-exercises/numpy/index-array.php

In [2]:
import numpy as np

1d array:

In [6]:
x = np.arange(5).reshape(5)
x

array([0, 1, 2, 3, 4])

2d array:

In [10]:
x = np.arange(8)
print(x)
print(x.shape)
x = x.reshape(2,4)
print(x); print(x.shape)

[0 1 2 3 4 5 6 7]
(8,)
[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


3d array:

In [14]:
x = np.arange(16).reshape(2,2,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [15]:
np.__version__

'1.22.4'

Escreva um programa NumPy para converter uma lista de valores numéricos em uma matriz NumPy bidimensional:

In [27]:
x = [1, 2, 3, 4]
print(type(x))
x = np.array(x).reshape(2,2)
print(type(x))
print(x)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


Escreva um programa NumPy para criar uma matriz 3x3 com valores variando de 2 a 10:

In [34]:
x = np.arange(2,11)
print(x,len(x))
print(x.reshape(3,3))

[ 2  3  4  5  6  7  8  9 10] 9
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


7

Escreva um programa NumPy para criar um vetor nulo de tamanho 10 e atualize o sexto valor para 11.

In [40]:
x = np.zeros(10)
print(x)
x[5]=11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


Escreva um programa NumPy para inverter uma matriz (o primeiro elemento se torna o último):

In [49]:
x = np.arange(11)
print(x)
print(x[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


Escreva um programa NumPy para converter uma matriz em um tipo flutuante:

In [53]:
x = np.arange(11)
x = np.asfarray(x)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Escreva um programa NumPy para criar uma matriz 2D com 1 na borda e 0 no interior:

In [60]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Escreva um programa NumPy para adicionar uma borda (preenchida com 0's) ao redor de um array existente:

In [76]:
x = np.ones((5,5))
print(x)
x[:1]=0; x[-1:]=0; x[:,:1]=0; x[:,-1:]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [81]:
x = np.ones((3,3))
print(x)
x = np.pad(x, pad_width=2, mode='constant', constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Escreva um programa NumPy para criar uma matriz 8x8 e preenchê-la com um padrão quadriculado:

In [101]:
x = np.ones((64))
print(x.shape)
x = x.reshape((8,8))
x[1::2,::2] = 0
x[::2,1::2] = 0
print(x, x.shape)

(64,)
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]] (8, 8)


Escreva um programa NumPy para converter uma lista e tupla em arrays.
List to array:

In [120]:
lista = [1, 2, 3, 4, 5]
print(type(lista))
tupla = ([1,2,4],[4,5,6])
print(type(tupla))
lista = np.array(lista)
print(lista, type(lista))
tupla = np.asarray(tupla)
print(tupla, type(tupla))


<class 'list'>
<class 'tuple'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2 4]
 [4 5 6]] <class 'numpy.ndarray'>


Escreva um programa NumPy para anexar valores ao final de uma matriz:

In [131]:
x = np.arange(10,31,10)
y = np.array([40, 50, 60])
x = np.append(x,[y,[70,80,90]])
print(x)

[10 20 30 40 50 60 70 80 90]
